server:
  port: 8080
  datasource:
    url: jdbc:mariadb://144.122.71.113:8083/group3
    username: group3
    password: TfRerYzuUGw2YLm
    driver-class-name: org.mariadb.jdbc.Driver


logging:
  level:
    org.springframework.security: TRACE
