server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 8dc33655b0c65feef737
            client-secret: a342159ea10e071e6ca58c25751cb2b433154fc2
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:mariadb://144.122.71.113:8083/group3
    username: group3
    password: TfRerYzuUGw2YLm
    driver-class-name: org.mariadb.jdbc.Driver


logging:
  level:
    org.springframework.security: TRACE
